The *rhel9-httpd* container includes a bash shell. In this step, you
will deploy the container in an interactive fashion, which will allow
you to run commands within the deployed container. In the #top terminal#
run the following:

[source,bash,run]
----
podman run -it rhel9-httpd /bin/bash
----

You should now be looking at a generic bash shell prompt:

In the `+Podman+` tab, the displayed shell is running inside the
container image, not the host operating system. To confirm this, take a
look at the mounted filesystems:

[source,bash,run]
----
df -hP
----

You will notice that all of the filesystem contents are either
memory-based (tmpfs, shm) or the overlay file associated with this
runtime of the container image (overlay).

Switch to the `+RHEL Host+` tab. Use this terminal to verify that the
container is running:

[source,bash,run]
----
podman ps -a
----

*Note:* Your CONTAINER ID and NAMES will be different than the output
displayed above as each container is assigned a unique ID and Name.
