---
virtualmachines:
  - name: "rhel"
    image: "rhel-10-0-06-17-25-2"
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
